### ISSUE TITLE
feature: Build a Footer for the page

### ISSUE THREAD

**Issue by RajeevDash007** [RajeevDash007/gsoc-github-finder#3]
You can design and code your own footer.
We can also discuss about designs to finalize one.
if you need any help, you can reach out me any time.

**Comment by mademoiselle-chantal** [comment]
Hello, @RajeevDash007! I would like to work on this issue.

**Comment by RajeevDash007** [comment]
> Hello, @RajeevDash007! I would like to work on this issue.

Sure!!! Go on,
Make another file named "footer.tsx" in the components folder, then route it in page.tsx


Don't forget to give a star ⭐️ to this repo

**Comment by mademoiselle-chantal** [comment]
Thank you! Regarding footer designs, can l use designs from Tailwind or do you have your suggestions? What do you reckon?

**Comment by RajeevDash007** [comment]
> Thank you! Regarding footer designs, can l use designs from Tailwind or do you have your suggestions? What do you reckon?

You can try your own tailwindcss design,
Before implementing, if you can share me the screenshot of the design, that would be enough👍

**Comment by mademoiselle-chantal** [comment]
Do you prefer this one with text on the right side and some social links on the left side?

<img width="1467" alt="Screenshot 2024-03-10 at 00 07 38" src="https://github.com/RajeevDash007/gsoc-github-finder/assets/120084609/b9da1ee7-a879-454a-9c23-efaa57268d86">

**Comment by mademoiselle-chantal** [comment]
Or do you prefer this one?

<img width="1469" alt="Screenshot 2024-03-10 at 00 10 18" src="https://github.com/RajeevDash007/gsoc-github-finder/assets/120084609/bdd67a69-c5e3-4e77-9504-5f84631d2a15">

**Comment by mademoiselle-chantal** [comment]
Looking at your website, l see that there's nothing much yet so that's why l went on with such designs with just some text and social links. You can recommend something better. It's all cool with me.

**Comment by RajeevDash007** [comment]
> Or do you prefer this one?
> 
> <img width="1469" alt="Screenshot 2024-03-10 at 00 10 18" src="https://github.com/RajeevDash007/gsoc-github-finder/assets/120084609/bdd67a69-c5e3-4e77-9504-5f84631d2a15">
> 

LGTM👍
